version: '2.1'
services:
  human-machine:
    image: docker-reg.ecovacs.com/library/human-machine:0.3.3-20200610-420f759
    container_name: human-machine
    ports:
      - "8127:8000"
    restart: always
    logging:
      options:
        max-size: "5M"
        max-file: "10"
      driver: json-file

