version: '2.1'
services:
  human-machine:
    image: docker-reg.ecovacs.com/library/human-machine:20191202-3c18c68
    container_name: human-machine
    ports:
      - "8000:8000"
    restart: always
    logging:
      options:
        max-size: "5M"
        max-file: "10"
      driver: json-file
