export default {
  FieldLabels: {
    roleId: '角色标识',
    roleName: '角色名称',
    description: '描述',
    roleManage: '角色管理',
    userManage: '用户管理',
    projectManage: '项目管理',
    templateManage: '标注模板管理',
    departmentManage: '机构管理',
    dataMark: '数据标注',
  },
  operateName: {
    add: '新增',
    modify: '修改',
    query: '查询',
    queryAll: '查询全部',
    delete: '删除',
    export: '导出',
    mark: '标注',
    review: '质检',
  },
  dialogInputOptions: [
    { label: '新增', value: 'add' },
  ],
  historyRecordOptions: [
    { label: '修改', value: 'modify' },
    { label: '查询', value: 'query' },
    { label: '删除', value: 'delete' },
    { label: '导出', value: 'export' },
  ],
  roleManageOptions: [
    { label: '新增', value: 'add' },
    { label: '修改', value: 'modify' },
    { label: '查询', value: 'query' },
    { label: '删除', value: 'delete' },
  ],
  userManageOptions: [
    { label: '新增', value: 'add' },
    { label: '修改', value: 'modify' },
    { label: '查询', value: 'query' },
    { label: '删除', value: 'delete' },
  ],
  projectManageOptions: [
    { label: '新增', value: 'add' },
    { label: '修改', value: 'modify' },
    { label: '查询', value: 'query' },
    { label: '删除', value: 'delete' },
    { label: '查询全部', value: 'queryAll' },
  ],
  templateManageOptions: [
    { label: '新增', value: 'add' },
    { label: '修改', value: 'modify' },
    { label: '查询', value: 'query' },
    { label: '删除', value: 'delete' },
  ],
  departmentManageOptions: [
    { label: '新增', value: 'add' },
    { label: '修改', value: 'modify' },
    { label: '查询', value: 'query' },
    { label: '删除', value: 'delete' },
  ],
  dataMarkOptions: [
    { label: '标注', value: 'mark' },
    { label: '质检', value: 'review' },
  ],
}
